Repository Clefspeare13/pornhosts, pull requests merged in 2020-09, with the labels that each got.

#234 pornedup.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#226 akiba-web.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#240 styles.lemmecheck.net
  submit_here/hosts.txt
Labels: CDN host, NSFW Adult Material

#212 lemmecheck.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#208 legalporno.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#241 www.porn-star.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#242 glam0ur.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#243 100bucksbabes.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#244 eroticbeauties.net
  submit_here/hosts.txt
Labels: NSFW Adult Material

#245 hqbabes.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#247 yourdoll.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#246 myporn.club
  submit_here/hosts.txt
Labels: NSFW Adult Material

#249 wetpussygames.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#250 5kporn.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#257 imagetwist.com
  submit_here/strict_adult.txt
Labels: NSFW Adult Material, Strict Adult, Strict list

#253 avsox.cyou
  submit_here/hosts.txt
Labels: NSFW Adult Material

#255 badgirlsblog.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#260 ssl-cdn.com
  submit_here/hosts.txt
Labels: CDN host, NSFW Adult Material

#268 cuckoldcom.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#273 daftsex.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#276 yuajav.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#277 javhaven.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#280 javbitcoin.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#281 uralesbian.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#282 tokyofacefuck.com
  submit_here/hosts.txt
Labels: NSFW Adult Material
