Repository Clefspeare13/pornhosts, pull requests merged in 2020-08, with the labels that each got.

#104 Why to contribute
  README.md
Labels: enhancement

#173 Removal: chicaswebcams.com
  0.0.0.0/hosts
  127.0.0.1/hosts
  Mobile_0_0_0_0/hosts
  SafeSearch/hosts
  download_here/0.0.0.0/hosts
  download_here/127.0.0.1/hosts
  download_here/mobile/hosts
  download_here/safesearch/0.0.0.0/hosts
  download_here/safesearch/127.0.0.1/hosts
  download_here/safesearch/mobile/hosts
  download_here/safesearch/strict/0.0.0.0/hosts
  download_here/safesearch/strict/127.0.0.1/hosts
  download_here/strict/0.0.0.0/hosts
  download_here/strict/127.0.0.1/hosts
  submit_here/hosts.txt
  submit_here/mobile.txt
  test_results/dead.hosts.txt
  test_results/dead.mobile.txt
  test_results/hosts.active.txt
  test_results/mobile.active.txt
  test_results/snuff.active.txt
  test_results/strict_adult.active.txt
Labels: Removal request

#181 18plusstream.net
  .github/PULL_REQUEST_TEMPLATE.md
  submit_here/hosts.txt
Labels: NSFW Adult Material

#187 www.redflava.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#198 babesrater.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#200 babepedia.com/
  submit_here/hosts.txt
Labels: NSFW Adult Material

#204 pornotor.org
  submit_here/hosts.txt
Labels: NSFW Adult Material

#210 europornstar.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#211 thenude.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#213 analvids.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#215 viralporn.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#216 jav.guru
  submit_here/hosts.txt
Labels: NSFW Adult Material

#219 jkseifukufetish.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#220 tokyokinky.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#223 covertjapan.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#224 focusarmy.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#225 nanairo.co
  submit_here/hosts.txt
Labels: NSFW Adult Material

#228 ejaver.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#229 hentai4free.net
  submit_here/hosts.txt
Labels: NSFW Adult Material

#230 jerkdolls.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#231 pornnetworkdeals.com
  submit_here/hosts.txt
Labels: NSFW Adult Material

#232 curvyerotic.com
  submit_here/hosts.txt
Labels: NSFW Adult Material
